server {
    listen 80;
    server_name localhost;

    # Sirve los archivos de React
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Esto es vital para que funcione el React Router (si lo usas)
        try_files $uri $uri/ /index.html;
    }

    # Redirige todo lo que empiece con /api/ al contenedor del backend
    location /api/ {
        # 'backend' es el nombre del servicio en tu docker-compose
        proxy_pass http://test-1-backend:3000/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
