services:
  db:
    image: postgres:15-alpine
    container_name: mi_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: counter_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal_network
    # FÍJATE: No hay sección "ports". No se puede acceder desde afuera.

  backend:
    build: ./backend
    container_name: mi_backend
    environment:
      DATABASE_URL: postgresql://root:rootpassword@db:5432/counter_db
    depends_on:
      - db
    networks:
      - internal_network
    # FÍJATE: No hay sección "ports". No se puede acceder desde afuera.

  frontend:
    build: ./frontend
    container_name: mi_frontend
    ports:
      - "80:80" # EL ÚNICO PUERTO EXPUESTO
    depends_on:
      - backend
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge

volumes:
  pgdata:
