services:
  db:
    image: postgres:15-alpine
    container_name: test1_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: counter_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal_app_network

  backend:
    build: ./backend
    container_name: test1_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://root:rootpassword@db:5432/counter_db
    depends_on:
      - db
    networks:
      - internal_app_network

  frontend:
    build: ./frontend
    container_name: test1_frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - internal_app_network
      - proxy_network

networks:
  internal_app_network:
    driver: bridge
  proxy_network:
    external: true

volumes:
  pgdata:
