name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull and Restart Docker
        run: |
          # 1. Ir a la carpeta
          cd /var/www/test-1

          # 2. Limpiar cualquier cambio local que bloquee el pull (por si acaso)
          git reset --hard origin/main

          # 3. Bajar los cambios
          git pull origin main

          # 4. Reconstruir (usamos el comando moderno 'docker compose')
          # Si tu sistema usa el viejo 'docker-compose' con guión, cámbialo abajo
          docker compose up -d --build

          # 5. Limpieza
          docker image prune -f
